apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  db: testdatabase
  user: testuser
  storage: /var/lib/postgresql/data/pgdata
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webdav
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-dp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: pass 
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: storage
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: pod-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: pod-storage
          persistentVolumeClaim:
            claimName: webdav
